import subprocess
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient
from mcp import Client

from app.config import get_settings
from app.database import SessionLocal
from app.extraction import service as extraction_service
from app.extraction.runner import (
    ExtractionFailed,
    ExtractionUnavailable,
    build_mcp_config,
    render_command,
    run_extraction,
)
from app.extraction.tools import AGENT_TOOLS_BY_ID, detect_tools
from app.mcp.server import create_mcp_server
from app.models import Document, ExtractionStatus, GraphEvidence, GraphNode
from app.storage.local import LocalStorageProvider


@pytest.fixture
def mcp_server():
    return create_mcp_server(
        SessionLocal, lambda: LocalStorageProvider(get_settings().upload_dir)
    )


@pytest.fixture
def auto_approve(monkeypatch):
    monkeypatch.setenv("ARC_AUTO_APPROVE", "1")


def create_course(client: TestClient, code: str) -> dict[str, Any]:
    response = client.post("/courses", json={"name": f"Course {code}", "code": code})
    assert response.status_code == 201
    return response.json()


def upload(client: TestClient, course_id: str, name: str = "lecture.md") -> dict[str, Any]:
    response = client.post(
        f"/courses/{course_id}/documents",
        data={"document_type": "LECTURE"},
        files={
            "file": (
                name,
                b"# Groups\n\nA cyclic group is generated by one element.\n",
                "text/markdown",
            )
        },
    )
    assert response.status_code == 201
    return response.json()


def evidence(
    document_id: str, excerpt: str = "A cyclic group is generated by one element."
) -> dict[str, Any]:
    return {
        "document_id": document_id,
        "source_location": {"page": 1, "section": "Groups"},
        "excerpt": excerpt,
        "confidence": 0.8,
    }


# Tool detection and settings ------------------------------------------------


def test_detect_tools_reports_every_known_agent_cli() -> None:
    tools = {tool["id"]: tool for tool in detect_tools()}
    assert {"claude", "codex", "gemini", "opencode", "cursor-agent"} <= set(tools)
    for tool in tools.values():
        assert tool["available"] is (tool["path"] is not None)
        assert "{prompt}" in tool["default_command"]


def test_extraction_settings_expose_detected_tools(client: TestClient) -> None:
    settings = client.get("/settings/extraction")
    assert settings.status_code == 200
    body = settings.json()
    assert body["enabled"] is True
    assert {tool["id"] for tool in body["tools"]} >= {"claude", "codex"}
    assert all("defaultCommand" in tool for tool in body["tools"])


def test_extraction_settings_can_be_changed_and_reset(client: TestClient) -> None:
    updated = client.put(
        "/settings/extraction",
        json={"toolId": "codex", "command": "codex exec {prompt}", "enabled": False},
    )
    assert updated.status_code == 200
    assert updated.json()["toolId"] == "codex"
    assert updated.json()["command"] == "codex exec {prompt}"
    assert updated.json()["enabled"] is False

    cleared = client.put("/settings/extraction", json={"command": ""})
    assert cleared.status_code == 200
    assert cleared.json()["commandOverride"] is None
    assert cleared.json()["command"] == AGENT_TOOLS_BY_ID["codex"].command

    assert client.put("/settings/extraction", json={"toolId": "nope"}).status_code == 422
    assert client.put("/settings/extraction", json={}).status_code == 422


# Running the agent ----------------------------------------------------------


def test_mcp_config_exposes_only_arc_with_auto_approval(tmp_path: Path) -> None:
    import json

    config = json.loads(build_mcp_config(tmp_path).read_text(encoding="utf-8"))
    assert list(config["mcpServers"]) == ["arc"]
    assert config["mcpServers"]["arc"]["env"]["ARC_AUTO_APPROVE"] == "1"
    assert config["mcpServers"]["arc"]["env"]["DATABASE_URL"] == get_settings().database_url


def test_render_command_substitutes_the_document_under_extraction(tmp_path: Path) -> None:
    command = render_command(
        'claude -p "{prompt}" --mcp-config "{mcp_config}"',
        course_id="course-1",
        document_id="document-1",
        mcp_config=tmp_path / "arc-mcp.json",
    )
    assert "course-1" in command
    assert "document-1" in command
    assert "arc-mcp.json" in command


def test_run_extraction_requires_a_configured_and_installed_command() -> None:
    with pytest.raises(ExtractionUnavailable):
        run_extraction(command_template="  ", course_id="c", document_id="d")
    with pytest.raises(ExtractionUnavailable, match="not installed"):
        run_extraction(
            command_template="arc-not-a-real-agent {prompt}", course_id="c", document_id="d"
        )


def test_run_extraction_reports_a_failing_agent() -> None:
    def failing(argv, cwd):
        return subprocess.CompletedProcess(argv, 3, "", "model refused")

    with pytest.raises(ExtractionFailed, match="model refused"):
        run_extraction(
            command_template="python {prompt}",
            course_id="c",
            document_id="d",
            runner=failing,
        )


def test_run_extraction_reports_a_timeout() -> None:
    def slow(argv, cwd):
        raise subprocess.TimeoutExpired(argv, 1)

    with pytest.raises(ExtractionFailed, match="did not finish"):
        run_extraction(
            command_template="python {prompt}", course_id="c", document_id="d", runner=slow
        )


# Document lifecycle ---------------------------------------------------------


def test_upload_processes_the_source_without_a_process_button(client: TestClient) -> None:
    course = create_course(client, "EX100")
    upload(client, course["id"])
    documents = client.get(f"/courses/{course['id']}/documents").json()
    assert documents[0]["processingStatus"] == "READY"
    assert documents[0]["chunkCount"] > 0


def test_extraction_records_success_on_the_document(client: TestClient, monkeypatch) -> None:
    course = create_course(client, "EX101")
    document = upload(client, course["id"])
    monkeypatch.setattr(
        extraction_service,
        "run_extraction",
        lambda **kwargs: extraction_service.ExtractionResult(command="agent", output="done"),
    )

    extracted = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")
    assert extracted.status_code == 200
    assert extracted.json()["extractionStatus"] == "COMPLETED"
    assert extracted.json()["extractionError"] is None
    assert extracted.json()["extractedAt"]


def test_a_missing_agent_keeps_the_chunks_and_explains_itself(
    client: TestClient, monkeypatch
) -> None:
    course = create_course(client, "EX102")
    document = upload(client, course["id"])

    def unavailable(**kwargs):
        raise ExtractionUnavailable("claude is not installed or not on PATH")

    monkeypatch.setattr(extraction_service, "run_extraction", unavailable)
    extracted = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")

    assert extracted.status_code == 200
    body = extracted.json()
    assert body["extractionStatus"] == "UNAVAILABLE"
    assert "not installed" in body["extractionError"]
    assert body["processingStatus"] == "READY"
    assert body["chunkCount"] > 0


def test_a_failing_agent_is_reported_and_retryable(client: TestClient, monkeypatch) -> None:
    course = create_course(client, "EX103")
    document = upload(client, course["id"])

    def failing(**kwargs):
        raise ExtractionFailed("claude exited with code 1: rate limited")

    monkeypatch.setattr(extraction_service, "run_extraction", failing)
    failed = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")
    assert failed.json()["extractionStatus"] == "FAILED"
    assert "rate limited" in failed.json()["extractionError"]

    monkeypatch.setattr(
        extraction_service,
        "run_extraction",
        lambda **kwargs: extraction_service.ExtractionResult(command="agent", output=""),
    )
    retried = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")
    assert retried.json()["extractionStatus"] == "COMPLETED"
    assert retried.json()["extractionError"] is None


def test_extraction_is_skipped_when_turned_off(client: TestClient) -> None:
    course = create_course(client, "EX104")
    document = upload(client, course["id"])
    client.put("/settings/extraction", json={"enabled": False})

    extracted = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")
    assert extracted.json()["extractionStatus"] == "UNAVAILABLE"
    assert "turned off" in extracted.json()["extractionError"]


def test_extraction_requires_processed_chunks(client: TestClient) -> None:
    course = create_course(client, "EX105")
    document = upload(client, course["id"], name="broken.md")
    with SessionLocal() as db:
        record = db.get(Document, document["id"])
        record.processing_status = "FAILED"
        db.commit()

    blocked = client.post(f"/courses/{course['id']}/documents/{document['id']}/extract")
    assert blocked.status_code == 409


# Auto-approved writes -------------------------------------------------------


@pytest.mark.anyio
async def test_agent_writes_land_in_the_graph_without_review(
    client: TestClient, mcp_server, auto_approve
) -> None:
    course = create_course(client, "EX106")
    document = upload(client, course["id"])

    async with Client(mcp_server) as mcp_client:
        first = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Cyclic group",
                **evidence(document["id"]),
            },
        )
        second = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Generator",
                **evidence(document["id"]),
            },
        )
        await mcp_client.call_tool(
            "create_candidate_relationship",
            {
                "course_id": course["id"],
                "source_node_id": first.structured_content["id"],
                "target_node_id": second.structured_content["id"],
                "relationship_type": "REQUIRES",
                **evidence(document["id"]),
            },
        )

    assert first.structured_content["review_status"] == "APPROVED"
    graph = client.get(f"/courses/{course['id']}/graph").json()
    assert sorted(node["label"] for node in graph["nodes"]) == ["Cyclic group", "Generator"]
    assert len(graph["edges"]) == 1
    queue = client.get(f"/courses/{course['id']}/graph/review/candidates").json()
    assert queue["pendingCount"] == 0


@pytest.mark.anyio
async def test_re_extraction_folds_into_existing_nodes_instead_of_duplicating(
    client: TestClient, mcp_server, auto_approve
) -> None:
    course = create_course(client, "EX107")
    first_document = upload(client, course["id"], "week-5.md")
    second_document = upload(client, course["id"], "week-6.md")

    async with Client(mcp_server) as mcp_client:
        original = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Cyclic group",
                **evidence(first_document["id"]),
            },
        )
        repeat = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "cyclic   group",
                "description": "Generated by a single element.",
                **evidence(second_document["id"], "Every cyclic group is abelian."),
            },
        )

    assert repeat.structured_content["id"] == original.structured_content["id"]
    graph = client.get(f"/courses/{course['id']}/graph").json()
    assert [node["label"] for node in graph["nodes"]] == ["Cyclic group"]
    with SessionLocal() as db:
        node = db.get(GraphNode, original.structured_content["id"])
        assert node.description == "Generated by a single element."
        assert db.query(GraphEvidence).filter_by(graph_node_id=node.id).count() == 2
        assert {
            item.document_id
            for item in db.query(GraphEvidence).filter_by(graph_node_id=node.id).all()
        } == {first_document["id"], second_document["id"]}


@pytest.mark.anyio
async def test_repeated_relationships_do_not_duplicate_edges(
    client: TestClient, mcp_server, auto_approve
) -> None:
    course = create_course(client, "EX108")
    document = upload(client, course["id"])

    async with Client(mcp_server) as mcp_client:
        source = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Cyclic group",
                **evidence(document["id"]),
            },
        )
        target = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Group",
                **evidence(document["id"]),
            },
        )
        payload = {
            "course_id": course["id"],
            "source_node_id": source.structured_content["id"],
            "target_node_id": target.structured_content["id"],
            "relationship_type": "REQUIRES",
            **evidence(document["id"]),
        }
        first = await mcp_client.call_tool("create_candidate_relationship", payload)
        second = await mcp_client.call_tool("create_candidate_relationship", payload)

    assert first.structured_content["id"] == second.structured_content["id"]
    assert len(client.get(f"/courses/{course['id']}/graph").json()["edges"]) == 1


@pytest.mark.anyio
async def test_candidates_still_need_review_when_auto_approval_is_off(
    client: TestClient, mcp_server, monkeypatch
) -> None:
    monkeypatch.delenv("ARC_AUTO_APPROVE", raising=False)
    course = create_course(client, "EX109")
    document = upload(client, course["id"])

    async with Client(mcp_server) as mcp_client:
        node = await mcp_client.call_tool(
            "create_candidate_node",
            {
                "course_id": course["id"],
                "node_type": "CONCEPT",
                "label": "Cyclic group",
                **evidence(document["id"]),
            },
        )

    assert node.structured_content["review_status"] == "PENDING"
    assert client.get(f"/courses/{course['id']}/graph").json()["nodes"] == []


def test_extraction_status_is_reported_per_document(client: TestClient) -> None:
    course = create_course(client, "EX110")
    upload(client, course["id"])
    documents = client.get(f"/courses/{course['id']}/documents").json()
    assert documents[0]["extractionStatus"] == ExtractionStatus.NOT_STARTED.value
