from pathlib import Path
from typing import BinaryIO, Protocol


class StorageProvider(Protocol):
    def save(self, stream: BinaryIO, filename: str) -> str: ...
    def delete(self, storage_path: str) -> None: ...
    def get(self, storage_path: str) -> Path: ...
